#!/bin/sh

help(){
    cat<<__EOF__
    usage:  m lock [ help ]

    Examples:
      m lock      # lock session
__EOF__
}

lock(){
    if [[ ($(sw_vers -productVersion | awk -F '.' '{print $1}') == "10") && ($(sw_vers -productVersion | awk -F '.' '{print $2}') -gt "8") ]]; then
        pmset displaysleepnow
    else
        /System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend
    fi
}

case $1 in
    help)
        help
        ;;
    *)
        lock
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
